config/routes.rb
Rails.application.routes.draw do

  # get 'favorit/create'
  # get 'favorit/destroy'
  root 'tweets#index'

  # get 'tweets/new'
  # get 'tweets/index'
  # get 'tweets/show'
  # get 'tweets/create'
  # get 'users/index'
  # get 'users/show'

  devise_for :users

  #ネスト（入れ子）にする do~end
  resources :tweets do
    resource :favorites, only: [:create, :destroy]
  end
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  #たくさん持たれる側（子供側）なのでbelongs_to
  belongs_to :user
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :favorites

 #ユーザーがツイートをファボ（いいね）したかどうかを判定
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets
  has_many :favorites
  # UserはたくさんのTweetを持っているため、関連付けをした(複数形)

  has_many :favorite_tweets, through: :favorites, source: :tweet
  #多対多え関連付けを行うときは、throughオプションを付けると、中間テーブルを経由して関連先のモデルを取得できるようになる。
  #source は参照元のモデルをさすオプション
  # 上のhas_many :tweetsと重複するために、has_many :favorite_tweetsと名称を変更している。
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.build(tweet_id: params[:tweet_id])
    favorite.save
    redirect_to tweet_path
    #こう記述することで、current_userに関連したfavoriteクラスの新しいインスタンスが生成可能
    #favorite.user_id = current_user.idが済んだ状態で生成される
    #buildはnewと同じ意味。
  end

  def destroy
    favorite = Favorite.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    favorite.destroy
    redirect_to tweets_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, expect: [:index]
  #deviseメソッドで「ログインしていないユーザーをログイン画面に送る」メソッド
  def new
    @tweet = Tweet.new
  end

 #保存
  def create
    @tweet = Tweet.new(tweet_params) #フォームから送られてきたデータ(body)をストロングパラメータを経由して@tweetに代入
    @tweet.user_id = current_user.id #user_idの情報はフォームから送られてないので、deviseのメソッドであるcurrent_userを@tweet.user_idに代入している
    @tweet.save
    redirect_to tweets_path
  end

  def index
    @tweets = Tweet.all
  end

  def show
    @tweet = Tweet.find(params[:id])
    @user = @tweet.user
  end

  private
   def tweet_params
     params.require(:tweet).permit(:body)
   end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets
    #ユーザーがファボしたツイートを取得できるようになる
    @favorite_tweets = @user.favorite_tweets
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorite_helper.rb
module FavoriteHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorite/create.html.erb
<h1>Favorite#create</h1>
<p>Find me in app/views/favorite/create.html.erb</p>

app/views/favorite/destroy.html.erb
<h1>Favorite#destroy</h1>
<p>Find me in app/views/favorite/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AssociationTutorial</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %> <!-- deviseのメソッドで、ログインしているかいないかで真偽値を返すメソッド -->
      <%= link_to "新規投稿", new_tweet_path %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      <%= link_to "マイページ", user_path(current_user.id) %>
    <% else %>
      <%= link_to "新規登録", new_user_registration_path %>
      <%= link_to "ログイン", new_user_session_path %>
    <% end %>
      <%= link_to "ツイート一覧", tweets_path %>
      <%= link_to "ユーザー一覧", users_path %>
    <%= yield %>
  </body>
</html>

app/views/tweets/create.html.erb
<h1>Tweets#create</h1>
<p>Find me in app/views/tweets/create.html.erb</p>

app/views/tweets/index.html.erb
<h1>Tweets#index</h1>
<p>Find me in app/views/tweets/index.html.erb</p>

<% @tweets.each do |tweet| %>
 <hr>
 <p><span>email: </span><%= link_to tweet.user.email, user_path(tweet.user.id) %></p>
 <p><span>ツイート内容: </span><%= link_to tweet.body, tweet_path(tweet.id) %></p>

 <% if user_signed_in? %>
  <% if tweet.favorited_by?(current_user) %>
    <p><span>お気に入り解除: </span><%=
    link_to tweet.favorites.count, tweet_favorites_path(tweet.id), method: :delete %></p>
  <% else %>
    <p><span>お気に入り登録: </span><%=
    link_to tweet.favorites.count, tweet_favorites_path(tweet.id), method: :post %></p>
  <% end %>
 <% else %>
  <p><span>お気に入り数: </span><%= tweet.favorites.count %></p>
 <% end %>
<% end %>

app/views/tweets/new.html.erb
<h1>Tweets#new</h1>
<p>Find me in app/views/tweets/new.html.erb</p>

<!-- ツイート画面 -->
<%= form_for @tweet do |f| %>
 <p>
   <%= f.label :body, "ツイート" %>
   <%= f.text_field :body %>
 </p>
 <%= f.submit %>
<% end %>

app/views/tweets/show.html.erb
<h1>Tweets#show</h1>
<p>Find me in app/views/tweets/show.html.erb</p>

<p><span>email: </span><%= @user.email %></p>
<p><span>ツイート内容: </span><%= @tweet.body %></p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<% @users.each do |user| %>
 <hr>
 <p><span>email: </span><%= link_to user.email, user_path(user.id) %></p>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<hr>
<p><span>email: </span><%= @user.email %></span>

<% @tweets.each do |tweet| %>
 <hr>
 <p><span>ツイート内容: </span><%= link_to tweet.body, tweet_path(tweet.id) %></p>
<% end %>

<% @favorite_tweets.each do |tweet| %>
 <hr>
 <p><span>ファボツイート内容: </span><%= link_to tweet.body, tweet_path(tweet.id) %></p>
<% end %>